name: EpicHoppers
description: EpicHoppers
main: com.songoda.epichoppers.EpicHoppers
depend: [Arconix]
softdepend: [Towny, RedProtect, Kingdoms, PlotsSquared, GriefPrevention, USkyBlock, ASkyBlock, WorldGuard, Factions, Vault]
version: 2.3.2
author: Songoda
commands:
  epichoppers:
    description: View information on this plugin.
    default: true
    aliases: [sc, eh, synccraft]
    usage: /eh